"""add source positions to document chunks

Revision ID: a8e43adc7ddf
Revises: 193148f52066
Create Date: 2026-09-21 17:09:12.720949

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a8e43adc7ddf'
down_revision = '193148f52066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentchunk', sa.Column('source_start', sa.Integer(), nullable=True))
    op.add_column('documentchunk', sa.Column('source_end', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentchunk', 'source_end')
    op.drop_column('documentchunk', 'source_start')
    # ### end Alembic commands ###
